# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install --global gulp-cli && npm i gulp
      - name: Npm install
        run: npm install
      - name: Gulp build
        run: gulp build
      - name: Docker login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: docker login -u paulrill -p $DOCKER_PASSWORD
      - name: Build Frontend Image
        run: docker build -f Dockerfile.frontend -t paulrill/reversi:frontend .
      - name: Build Latest Image
        run: docker build -f Dockerfile.latest -t paulrill/reversi:latest .
      - name: Push Backend image
        run: docker push paulrill/reversi:backend
      - name: Push Latest image
        run: docker push paulrill/reversi:latest
      - name: Restart Docker Container
        env:
          PORTAINER_URL: ${{ secrets.PORTAINER_URL }}
        run: curl --location --request POST $PORTAINER_URL
